export const DRIVETRAINS = {
  tank: {
    id: "tank",
    name: "Tank Drive",
    description:
      "The most common and straightforward drivetrain. Two sets of wheels on either side, each powered independently. Simple, reliable, and powerful.",
    complexity: 1,
    cost: 1,
    maneuverability: 2,
    programmingDifficulty: 1,
    minMotors: 2,
    buildTimeHours: "4-8",
    pros: [
      "High torque efficiency",
      "Simple to build and maintain",
      "Predictable kinematics",
      "Low cost",
      "Easy programming",
      "Excellent pushing power",
    ],
    cons: [
      "Cannot strafe sideways",
      "Limited maneuverability",
      "Larger turning radius",
      "Wheel slip during turns",
      "Slower repositioning",
    ],
    bestFor: [
      "Fast-paced games requiring speed",
      "Pushing heavy objects",
      "Simple autonomous routines",
      "First-time builders",
      "Limited budget",
    ],
    avoidFor: [
      "Games requiring precise positioning",
      "Tight spaces with many obstacles",
      "Tasks needing omnidirectional movement",
    ],
    wheelConfiguration: "2-4 wheels per side, typically 4 or 6 total wheels",
  },
  mecanum: {
    id: "mecanum",
    name: "Mecanum Drive",
    description:
      "Holonomic drivetrain using special wheels with rollers at 45° angles. Can move in any direction without rotating the chassis.",
    complexity: 3,
    cost: 3,
    maneuverability: 4,
    programmingDifficulty: 3,
    minMotors: 4,
    buildTimeHours: "8-16",
    pros: [
      "Omnidirectional movement (strafing)",
      "No need to rotate for positioning",
      "Excellent maneuverability",
      "Good for tight spaces",
      "Field-centric control possible",
    ],
    cons: [
      "Reduced traction vs. standard wheels",
      "More expensive (special wheels)",
      "Complex programming (vector math)",
      "Diagonal drift issues",
      "Uneven wheel wear",
      "Lower pushing power",
    ],
    bestFor: [
      "Games requiring precise positioning",
      "Navigating tight spaces",
      "Quick directional changes",
      "Advanced teams",
    ],
    avoidFor: [
      "Pushing matches",
      "Slippery surfaces",
      "Budget-constrained teams",
      "First-time builders",
    ],
    wheelConfiguration:
      "4 mecanum wheels in X-pattern (LF & RR same, RF & LR opposite)",
  },
  swerve: {
    id: "swerve",
    name: "Swerve Drive",
    description:
      "The ultimate drivetrain. Each wheel can rotate and drive independently, offering complete control over movement and rotation.",
    complexity: 5,
    cost: 5,
    maneuverability: 5,
    programmingDifficulty: 5,
    minMotors: 8,
    buildTimeHours: "40-80",
    pros: [
      "Ultimate maneuverability",
      "True omnidirectional movement",
      "Can rotate while moving",
      "Excellent traction",
      "Precise control",
      "Impressive capability",
    ],
    cons: [
      "Extremely complex to build",
      "Very expensive ($500-1500)",
      "Requires 2 motors per module",
      "Difficult programming (inverse kinematics)",
      "Heavy",
      "Long build time",
      "Needs absolute encoders",
    ],
    bestFor: [
      "Experienced teams with resources",
      "Games requiring ultimate precision",
      "Showcasing technical capability",
      "FRC competitions",
    ],
    avoidFor: [
      "FTC teams (usually overkill)",
      "Limited budgets",
      "First-year teams",
      "Simple game tasks",
      "Time-constrained builds",
    ],
    wheelConfiguration: "4 independent swerve modules (2 motors each: drive + rotation)",
  },
  omni: {
    id: "omni",
    name: "Omni Drive",
    description:
      "Holonomic drivetrain using omni wheels with rollers perpendicular to the wheel. Faster than mecanum but similar capabilities.",
    complexity: 2,
    cost: 2,
    maneuverability: 4,
    programmingDifficulty: 2,
    minMotors: 3,
    buildTimeHours: "6-12",
    pros: [
      "Omnidirectional movement",
      "Faster than mecanum",
      "Simpler programming than mecanum",
      "Good maneuverability",
      "Multiple configurations (X, H, Kiwi)",
      "Lower cost than mecanum",
    ],
    cons: [
      "Less traction than standard wheels",
      "Wheel slippage in turns",
      "Some configurations need more space",
      "Can be less intuitive to drive",
    ],
    bestFor: [
      "Fast-paced games",
      "Teams wanting holonomic without mecanum cost",
      "Versatile performance",
      "Balanced approach",
    ],
    avoidFor: [
      "Heavy pushing required",
      "Maximum traction needed",
      "Very tight spaces (depending on config)",
    ],
    wheelConfiguration:
      "Various: X-drive (4 at 45°), H-drive (4 drive + 2 strafe), Kiwi (3 at 120°)",
  },
};

export const DRIVETRAIN_ORDER = ["tank", "mecanum", "swerve", "omni"];
